spring:
  application:
    name: packtory_de

  profiles:
    active: ${profile-active}

    group:
      dev1 : local,common
      dev2 : classroom,common
      prod : itwill,common
---
# 개인작업 설정 시작(H2 사용)
server:
  port: ${dev1-server-port}
spring:
  config:
    activate:
      on-profile: local

  devtools:
    livereload:
      enabled: ${dev1-tools-enable}
    restart:
      enabled: ${dev1-tools-enable}

  servlet:
    multipart:
      location: ${dev1-multipart_location}

  datasource:
    hikari:
      driver-class-name: ${dev1-db-driver}
      jdbc-url: ${dev1-db-url}
      username: ${dev1-db-user}
      password: ${dev1-db-password}

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    open-in-view: false # [WARN] spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning -> false를 하자!
    show_sql: true
    #database-platform: org.hibernate.dialect.H2Dialect #[WARN]HHH90000025 발생 -> "hibernate.dialect"를 명시적으로 지정할 필요가 없음
    hibernate:
      ddl-auto: create
# 개인작업 설정 끝(H2 사용)
---
# 수업시간 설정 시작(개인컴퓨터 MySQL사용)
server:
  port: ${dev2-server-port}
spring:
  config:
    activate:
      on-profile: classroom

  devtools:
    livereload:
      enabled: ${dev2-tools-enable}
    restart:
      enabled: ${dev2-tools-enable}

  servlet:
    multipart:
      location: ./uploads/

  datasource:
    hikari:
      driver-class-name: ${dev2-db-driver}
      jdbc-url: ${dev2-db-url}
      username: ${dev2-db-user}
      password: ${dev2-db-password}

  jpa:
    show_sql: true
    database-platform: ${dev2-db-jpa-platform}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
# 수업시간 설정 끝 (개인컴퓨터 MySQL사용)
---
# 공통 설정 시작
spring:
  config:
    activate:
      on-profile: common

# 로케이션은 각각 빼야 할것 같다.
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    hikari:
      pool-name: Hikari Connection Pool
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
# 공통 설정 끝