spring:
  application:
    name: packtory_de

  profiles:
    active: dev
    group:
      dev : mysql,common
      prod : oracle,common
---
# 개발 셋팅 - Mysql 시작
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: mysql
    import:
    - /packtory/properties/application-dev.yml

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
# 개발 기본 세팅 끝
---
# 개발 세팅 - Oracle 시작 
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: oracle
    import:
    - /packtory/properties/application-prod.yml

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
# 개발 세팅 - Oracle 끝
---
# 공통 설정 시작
spring:
  config:
    activate:
      on-profile: common

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    hikari:
      pool-name: Hikari Connection Pool
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 300000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 300000
      auto-commit: true
# 공통 설정 끝