spring:
  application:
    name: packtory_de

  profiles:
    active: dev
    group:
      dev : local,common
      prod : itwill,common
---
# local 시작
server:
  port: 8080
  servlet:
    session:
      persistent: false # Exception loading sessions from persistent storage java.lang.ClassCastException: class java.io.ObjectStreamClass cannot be cast to class java.lang.String

spring:
  config:
    activate:
      on-profile: local
    import:
    - optional:file:/packtory/properties/application-dev.yml
    #- /usr/local/tomcat/packtory/properties/application-itwill.yml

  datasource:
    hikari:
      driver-class-name: ENC(+fppC6nxEyOwnWgptbN0jOM9ecbXuJBdI6dFHjZZhojriGbASrof9w7GvoZ7YnuRmtWm787tu1/TNHOHaFbAVA==)
      jdbc-url: ENC(0xKylZjamyV1a4XW8K8X03xemZ3eJDOXCS8G0bBC8AESQXwcv4OgSbpgqmvXCB5ytYXrVx1LuOt2jOlYrVK83nwN94xPYfcq5Asqdjz6Zz+zuOHbNxDMa6F9+PQCx3vmjWeSI00gUFsKgzgtjbIV2HAjvBuLUH4kG2uCaOCf58M=)
      #jdbc-url: ENC(TbdPTXsAmksM6d0kOMpcmJOjq6kTAJhHK2rC4ohwKHzrKUTeeczN3TmAcwClNo50GvMLUn4OLsd78/TCz9dmmd6guru64jE+CzSuTIJ92k6nO/GrPtOKPVJfzrrj90NdxEYyWtVZNyJpsR54AzxbvA1dZhayfvZZREsSt8PxJZQ=)
      username: ENC(VCL5G7bqOxkj2KLddRPqPftdxrRUb2/01/+igfG5fASx6xa0sO6vlGDzOBJS7zcl)
      password: ENC(C77lbFalrra3yTIM45vXLvbzTtHYpj9U9EaCp5AfC6oZY7tr15MiNZvqXnt9N6HtXM91fmmN0jCItP/og7kkQg==)

  jpa:
    show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  aop:
    auto: true
# 로깅 커스텀 환경 변수 LogUtil 클래스 참고
logging:
  default:
    enabled: true
  detailed:
    enabled: true
    level: INFO
# local 끝
---
# 개발 세팅 - itwill 시작 
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: itwill
    import:
    - /packtory/properties/application-prod.yml

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
# 로깅 커스텀 환경 변수 LogUtil 클래스 참고
logging:
  default:
    enabled: false
  detailed:
    enabled: true
    level: TRACE
# 개발 세팅 - itwill 끝
---
# 공통 설정 시작
spring:
  config:
    activate:
      on-profile: common

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    hikari:
      pool-name: Hikari Connection Pool
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 300000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 300000
      auto-commit: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, caches, metrics  # or include: "*"

  endpoint:
    caches:
      enabled: true
# 공통 설정 끝