spring:
  application:
    name: packtory_de

  profiles:
    active: dev1

    group:
      dev1 : local,common
      dev2 : classroom,common
      prod : itwill,common
---
# 개인작업 설정 시작(H2 사용)
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  servlet:
    multipart:
      location: ./uploads/

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:./data/packtory_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    open-in-view: false # [WARN] spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning -> false를 하자!
    show_sql: true
    #database-platform: org.hibernate.dialect.H2Dialect #[WARN]HHH90000025 발생 -> "hibernate.dialect"를 명시적으로 지정할 필요가 없음
    hibernate:
      ddl-auto: create
# 개인작업 설정 끝(H2 사용)
---
# 수업시간 설정 시작(개인컴퓨터 MySQL사용)
server:
  port: 8090
spring:
  config:
    activate:
      on-profile: classroom

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  servlet:
    multipart:
      location: ./uploads/

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/testdb
      username: root
      password: 1234

  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
# 수업시간 설정 끝 (개인컴퓨터 MySQL사용)
---
# 훗날 해야 할 배포 설정 시작 (학원서버 Oracle 사용)
server:
  port: 9999
spring:
  config:
    activate:
      on-profile: itwill

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@itwillbs.com:1602:ORCL2412
    username: c##c4d2503t2
    password: itwillbs2503t2

  servlet:
    multipart:
      location: ./uploads/ # TODO 학원 서버 폴더 변경 필요
      
  jpa:
    show_sql: true
    database-platform: 
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #dialect: 
# 훗날 해야 할 배포 설정 끝 (학원서버 Oracle 사용)
---
# 공통 설정 시작
spring:
  config:
    activate:
      on-profile: common

  mvc:
    hiddenmethod:
      filter:
        enabled: true

# 로케이션은 각각 빼야 할것 같다.
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
#      location: ./uploads/

  datasource:
    hikari:
      pool-name: Hikari Connection Pool
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
# 공통 설정 끝