create table t_commoncode (
	idx numeric generated by default as identity primary key,
	id VARCHAR(50),
	name VARCHAR(50),
	description VARCHAR(100),
	reg_id VARCHAR(50),
	reg_date TIMESTAMP
);

create table t_commoncode_items (
	idx numeric generated by default as identity primary key,
	major_id VARCHAR(50),
	id VARCHAR(50),
	name VARCHAR(50),
	description VARCHAR(100),
	is_deleted VARCHAR(2),
	rank VARCHAR(6),
	reg_id VARCHAR(50),
	reg_date TIMESTAMP,
	mod_id VARCHAR(50),
	mod_date TIMESTAMP
);

create table t_files (
	idx numeric generated by default as identity primary key,
	major_type VARCHAR(50),
	major_id VARCHAR(50),
	file_path VARCHAR(50),
	file_name VARCHAR(50),
	file_size VARCHAR(10),
	rank VARCHAR(2),
	is_deleted VARCHAR(2),
	reg_id VARCHAR(50),
	reg_date TIMESTAMP
);

create table t_notice (
	idx numeric generated by default as identity primary key,
	type varchar(50),
	title varchar(50),
	contents varchar(255),
	is_banner varchar(2),
	is_deleted varchar(2),
	read_count numeric,
	file_idxs varchar(50),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_approval (
	idx numeric generated by default as identity primary key,
	type varchar(50),
	document_code varchar(50),
	title varchar(50),
	contents varchar(255),
	drafter_id varchar(50),
	status varchar(50),
	draft_date TIMESTAMP,
	due_date TIMESTAMP,
	form_template varchar(50),
	approver1_id varchar(50),
	approver2_id varchar(50),
	approver3_id varchar(50),
	approver1_sign varchar(50),
	approver2_sign varchar(50),
	approver3_sign varchar(50),
	approver1_date TIMESTAMP,
	approver2_date TIMESTAMP,
	approver3_date TIMESTAMP,
	approver1_signature varchar(50),
	approver2_signature varchar(50),
	approver3_signature varchar(50),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_policy (
	idx numeric generated by default as identity primary key,
	type varchar(50),
	title varchar(50),
	contents varchar(50),
	status varchar(50),
	file_idxs varchar(50),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_message (
	idx numeric generated by default as identity primary key,
	type varchar(50),
	title varchar(50),
	contents varchar(255),
	sender_id varchar(50),
	send_date TIMESTAMP,
	receiver_id varchar(50),
	receive_date TIMESTAMP
);

create table t_salary (
	idx numeric generated by default as identity primary key,
	employee_id varchar(50),
	base_salary varchar(50),
	payment_date TIMESTAMP,
	benefit_code varchar(50),
	benefit_amount numeric,
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_benefit (
	idx numeric generated by default as identity primary key,
	employee_id varchar(50),
	category varchar(50),
	code varchar(50),
	benefit_name varchar(50),
	rank varchar(50),
	tax_exempt_type varchar(50),
	payment_type varchar(50),
	calculation_rule varchar(200),
	calculation_technique varchar(50),
	is_deleted varchar(50),
	active_date varchar(50),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_client (
	idx numeric generated by default as identity primary key,
	business_number varchar(50),
	business_name varchar(50),
	company_name varchar(50),
	owner_name varchar(50),
	company_category varchar(50),
	company_subject varchar(50),
	phone_number varchar(50),
	e_mail varchar(50),
	fax_number varchar(50),
	address1 varchar(50),
	address2 varchar(50),
	credit_limit varchar(50),
	is_deleted varchar(50),
	memo varchar(50),
	status varchar(50),
	status_message varchar(50),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_client_info (
	idx numeric generated by default as identity primary key,
	business_number varchar(50),
	client_employee_name varchar(50),
	client_employee_memo varchar(250),
	phone1 varchar(50),
	phone2 varchar(50),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_order (
	idx numeric generated by default as identity primary key,
	document_number varchar(50),
	trade_code varchar(50),
	status_code varchar(50),
	business_name varchar(50),
	business_number varchar(50),
	request_date varchar(50),
	expected_date varchar(50),
	due_date varchar(50),
	destination_name varchar(50),
	reciver varchar(50),
	phone1 varchar(50),
	phone2 varchar(50),
	post_code varchar(10),
	address1 varchar(100),
	address2 varchar(100),
	special_issue varchar(200),
	is_deleted varchar(2),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_order_detail (
	idx numeric generated by default as identity primary key,
	document_number varchar(50),
	department_code varchar(50),
	client_name varchar(50),
	client_phone varchar(50),
	lot_number varchar(50),
	invoice_issue varchar(50),
	payment_status varchar(50),
	unissued_status varchar(50),
	supply_amount varchar(50),
	vat_amount varchar(50),
	total_amount varchar(50),
	issue_code varchar(50),
	issue_remaks varchar(50),
	is_deleted varchar(2),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);


create table t_order_items (
	idx numeric generated by default as identity primary key,
	order_document_number varchar(50),
	product_code varchar(50),
	product_number varchar(50),
	product_name varchar(50),
	product_value varchar(50),
	unit_price numeric,
	total_price numeric,
	is_deleted varchar(2),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_commute (
	idx numeric generated by default as identity primary key,
	employee_id varchar(50),
	work_status_code varchar(50),
	reg_date TIMESTAMP
);



create table t_employee (
    idx numeric generated by default as identity primary key,
    id varchar(50),
    name varchar(50),
    ssn varchar(50),
    department_code varchar(50),
    sub_department_code varchar(50),
    position_code varchar(50),
    resignation_date TIMESTAMP,
    hire_date TIMESTAMP,
    work_experience varchar(50),
    reg_id varchar(50),
    reg_date TIMESTAMP,
    mod_id varchar(50),
    mod_date TIMESTAMP
);

create table t_employee_detail (
	idx numeric generated by default as identity primary key,
	id varchar(50),
	phone_number varchar(50),
	email varchar(50),
	gender varchar(50),
	address1 varchar(100),
	address2 varchar(100),
	file_idxs varchar(50),
	salary_bank_code varchar(50),
	salary_bank_name varchar(50),
	salary_account_number varchar(50),
	salary_account_holder varchar(50),
	has_vehicle varchar(2),
	employee_status_code varchar(50),
	status_start_date TIMESTAMP,
	status_end_date TIMESTAMP,
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);


create table t_employee_promotion_history (
	idx numeric generated by default as identity primary key,
	employee_id varchar(50),
	prev_department_code varchar(50),
	prev_position_code varchar(50),
	new_department_code varchar(50),
	new_position_code varchar(50),
	promotion_date TIMESTAMP,
	waiting_date TIMESTAMP,
	approval_date TIMESTAMP,
	manager_id varchar(50),
	manager_name varchar(50),
	promotion_type varchar(50),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);

create table t_log (
	idx numeric generated by default as identity primary key,
	accessId varchar(50),
	accessType varchar(2),
	accessDevice varchar(2),
	ip varchar(20),
	parameters character varying(1000),
	url varchar(50),
	accessDate TIMESTAMP
);


create table t_menu (
	IDX	NUMERIC generated by default as identity primary key,
	MENU_TYPE	CHARACTER VARYING(10),
	MENU_ID	CHARACTER VARYING(10),
	RANK	CHARACTER VARYING(3),
	URL	CHARACTER VARYING(50),
	DESCRIPTION	CHARACTER VARYING(50),
	IS_DELETED	CHARACTER VARYING(2),
	REG_ID	CHARACTER VARYING(50),
	REG_DATE	TIMESTAMP,
	MOD_ID	CHARACTER VARYING(50),
	MOD_DATE	TIMESTAMP
)



---seq----------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS seq_emp_id START WITH 10000 INCREMENT BY 1;
drop sequence SEQ_EMP_ID;

CREATE SEQUENCE IF NOT EXISTS seq_doc_number START WITH 100000 INCREMENT BY 1;
drop sequence seq_doc_number;

CREATE SEQUENCE IF NOT EXISTS seq_order_number START WITH 100000 INCREMENT BY 1;
drop sequence seq_order_number;

---seq----------------------------------------------------------

-- 작성할 임시 테이블
create table t_temp (
	idx numeric generated by default as identity primary key,
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	 varchar(50),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);



---drop----------------------------------------------
create table t_employee (
	idx numeric generated by default as identity primary key,
	id varchar(50),
	name varchar(50),
	department_code varchar(50),
	sub_department_code varchar(50),
	position_code varchar(50),
	phone_number varchar(50),
	email varchar(50),
	gender varchar(50),
	ssn varchar(50),
	address1 varchar(100),
	address2 varchar(100),
	hire_date TIMESTAMP,
	resignation_date TIMESTAMP,
	work_experience varchar(50),
	salary_bank_code varchar(50),
	salary_bank_name varchar(50),
	salary_account_number varchar(50),
	salary_account_holder varchar(50),
	has_vehicle varchar(2),
	employee_status_code varchar(50),
	status_start_date TIMESTAMP,
	status_end_date TIMESTAMP,
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);
drop table t_employee;
---drop----------------------------------------------
create table t_order (
	idx numeric generated by default as identity primary key,
	document_number varchar(50),
	trade_code varchar(50),
	status_code varchar(50),
	business_name varchar(50),
	business_number varchar(50),
	request_date varchar(50),
	expected_date varchar(50),
	due_date varchar(50),
	department_code varchar(50),
	client_name varchar(50),
	client_phone varchar(50),
	destination_name varchar(50),
	reciver varchar(50),
	phone1 varchar(50),
	phone2 varchar(50),
	address1 varchar(100),
	address2 varchar(100),
	special_issue varchar(200),
	lot_number varchar(50),
	invoice_issue varchar(50),
	payment_status varchar(50),
	unissued_status varchar(50),
	supply_amount varchar(50),
	vat_amount varchar(50),
	total_amount varchar(50),
	issue_code varchar(50),
	issue_remaks varchar(50),
	is_deleted varchar(2),
	reg_id varchar(50),
	reg_date TIMESTAMP,
	mod_id varchar(50),
	mod_date TIMESTAMP
);
drop table t_order;
---drop----------------------------------------------